require "timecop"
require "stay_gold"

RSpec.describe StayGold do
  let(:staygold_path) { ROOT_PATH.join("tmp", "stay_gold") }

  context "record" do
    it "records stdout, stderr, and status to a single yaml" do
      time = Time.now
      Timecop.freeze(time)
      result = StayGold.record(record_as: "echo_hello") do
        Open3.capture3("echo hello")
      end
      expect(result.commands.size).to eq(1)
      expect(result.commands.first.class).to eq(Open3::Capture3)
      expect(result.commands.first.args).to eq(["echo", "hello"])
      expect(result.cassette_path).to eq(staygold_path.join("echo_hello.yaml"))
      expect(staygold_path.join("echo_hello.yaml")).to exist
      results = YAML.load_file(staygold_path.join("echo_hello.yaml"))
      expect(results).to be_a(Array)
      expect(results.size).to eq(1)
      expect(results.first).to eq({
        "stdout" => "hello\n",
        "stderr" => "",
        "status" => 0,
        "recorded_at" => time.iso8601
      })

      expect(StayGold.output).to eq("hello\n")
    end

    it "records to an autogenerated path if no record_as is provided" do
      result = StayGold.record do
        Open3.capture3("echo hello")
      end
      # Path should be based off of spec name, describe block, context block
      expect(result.cassette_path.to_s).to match(%r{tmp/stay_gold/StayGold/record/records_to_an_autogenerated_path_if_no_record_as_is_provided\.yaml$})
      expect(result.cassette_path).to exist
    end

    it "records multiple commands to an array in the cassette" do
      time = Time.now
      Timecop.freeze(time)
      
      result = StayGold.record(record_as: "multi_command") do
        Open3.capture3("echo first")
        Open3.capture3("echo second")
        Open3.capture3("echo third")
      end
      
      expect(result.commands.size).to eq(3)
      expect(result.commands[0].args).to eq(["echo", "first"])
      expect(result.commands[1].args).to eq(["echo", "second"])
      expect(result.commands[2].args).to eq(["echo", "third"])
      
      expect(result.cassette_path).to exist
      cassette_data = YAML.load_file(result.cassette_path)
      
      # Multiple commands should be stored as an array
      expect(cassette_data).to be_a(Array)
      expect(cassette_data.size).to eq(3)
      
      expect(cassette_data[0]).to eq({
        "stdout" => "first\n",
        "stderr" => "",
        "status" => 0,
        "recorded_at" => time.iso8601
      })
      
      expect(cassette_data[1]).to eq({
        "stdout" => "second\n", 
        "stderr" => "",
        "status" => 0,
        "recorded_at" => time.iso8601
      })
      
      expect(cassette_data[2]).to eq({
        "stdout" => "third\n",
        "stderr" => "",
        "status" => 0, 
        "recorded_at" => time.iso8601
      })
      
      # last_output should be the last command
      expect(StayGold.output).to eq("third\n")
    end
  end
end