require "timecop"
require "stay_gold"

RSpec.describe StayGold do
  let(:staygold_path) { ROOT_PATH.join("tmp", "stay_gold") }

  context "record" do
    it "records stdout, stderr, and status to a single yaml" do
      time = Time.now
      Timecop.freeze(time)
      result = StayGold.record(record_as: "echo_hello") do
        Open3.capture3("echo hello")
      end
      expect(result.commands.size).to eq(1)
      expect(result.commands.first.class).to eq(Open3::Capture3)
      expect(result.commands.first.args).to eq(["echo", "hello"])
      expect(result.cassette_path).to eq(staygold_path.join("echo_hello.yaml"))
      expect(staygold_path.join("echo_hello.yaml")).to exist
      results = YAML.load_file(staygold_path.join("echo_hello.yaml"))
      expect(results).to eq({
        "stdout" => "hello\n",
        "stderr" => "",
        "status" => 0,
        "recorded_at" => time.iso8601
      })

      expect(StayGold.output).to eq("hello\n")
    end

    it "records to an autogenerated path if no record_as is provided" do
      result = StayGold.record do
        Open3.capture3("echo hello")
      end
      # Path should be based off of spec name, describe block, context block
      expect(result.cassette_path.to_s).to match(%r{tmp/stay_gold/StayGold/record/records_to_an_autogenerated_path_if_no_record_as_is_provided\.yaml$})
      expect(result.cassette_path).to exist
    end
  end
end