source "https://rubygems.org"

gem "railties", "~> 8.0"
gem "activerecord", "~> 8.0"
gem "activejob", "~> 8.0"
gem "actionpack", "~> 8.0"
gem "actioncable", "~> 8.0"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
end
